const redux = {
  API_ERROR: 'API_ERROR',

  FETCH_LIST_BREED: 'FETCH_LIST_BREED',
  RECEIVE_LIST_BREED: 'RECEIVE_LIST_BREED',

  FETCH_LIST_SUB_BREED: 'FETCH_LIST_SUB_BREED',
  RECEIVE_LIST_SUB_BREED: 'RECEIVE_LIST_SUB_BREED',

  FETCH_IMAGE_BREED: 'FETCH_IMAGE_BREED',
  RECEIVE_IMAGE_BREED: 'RECEIVE_IMAGE_BREED',

  FETCH_IMAGE_SUB_BREED: 'FETCH_IMAGE_SUB_BREED',
  RECEIVE_IMAGE_SUB_BREED: 'RECEIVE_IMAGE_SUB_BREED',

  FETCH_LIST_IMAGE_ALL_BREEDS: 'FETCH_LIST_IMAGE_ALL_BREEDS',
  RECEIVE_LIST_IMAGE_ALL_BREEDS: 'RECEIVE_LIST_IMAGE_ALL_BREEDS',
};

export default redux;
